# Dependencies
markdown:            redcarpet
highlighter:         pygments
excerpt_separator:   ''

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Maik Klein's
tagline:             'Blog'
description:         'Blog'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Maik Klein
  url:               https://github.com/MaikKlein
  email:             maikklein@googlemail.com

# Custom vars
version:             1.0.0
